# -*- coding: utf-8 -*-
"""LSTM+XGBoost perplexity fr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLmusFHUwFfiwQrxNkozHAW9c6wKCfP7
"""

import os, time, tempfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

import xgboost as xgb

# -------------------------
# Config
# -------------------------
FILE_WEATHER = "/content/drive/MyDrive/data/UTD_Weather.csv"
FILE_PV      = "/content/drive/MyDrive/data/UTD_Load.csv"

TIMESTEPS   = 48
BATCH_SIZE  = 32
EPOCHS      = 100
PATIENCE    = 15
THRESHOLD_DAY = 0.1
TARGET_PV   = "GHI"
TARGET_LOAD = "B4"

PANEL_AREA_M2    = 1.0
PANEL_EFFICIENCY = 0.20

# -------------------------
# Load & preprocess
# -------------------------
weather_df = pd.read_csv(FILE_WEATHER)
load_df    = pd.read_csv(FILE_PV)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp']    = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on="Timestamp", how="inner").sort_values("Timestamp").reset_index(drop=True)
df = df.dropna(subset=[TARGET_PV, TARGET_LOAD])

# Define features including time features
BASE_FEATURES = ['Temperature', 'Dew.Point', 'Relative.Humidity', 'Pressure', 'Wind.Speed',
                 'Wind.Direction', 'Cloud.Type', 'Solar.Zenith.Angle', 'Precipitable.Water',
                 'DNI', 'DHI']

# Add time features
df['hour'] = df['Timestamp'].dt.hour
df['dayofweek'] = df['Timestamp'].dt.dayofweek
df['month'] = df['Timestamp'].dt.month
df['hour_sin']  = np.sin(2*np.pi*df['hour']/24)
df['hour_cos']  = np.cos(2*np.pi*df['hour']/24)
df['dow_sin']   = np.sin(2*np.pi*df['dayofweek']/7)
df['dow_cos']   = np.cos(2*np.pi*df['dayofweek']/7)
df['mon_sin']   = np.sin(2*np.pi*df['month']/12)
df['mon_cos']   = np.cos(2*np.pi*df['month']/12)
TIME_FEATS = ['hour_sin','hour_cos','dow_sin','dow_cos','mon_sin','mon_cos']
FEATURES = BASE_FEATURES + TIME_FEATS


# -------------------------
# Helpers
# -------------------------
def create_sequences(X, y, timesteps):
    Xs, ys = [], []
    for i in range(len(X) - timesteps):
        Xs.append(X[i:i+timesteps])
        ys.append(y[i+timesteps])
    return np.array(Xs), np.array(ys)

def safe_mape(y_true, y_pred):
    mask = y_true > THRESHOLD_DAY
    if mask.sum() == 0: return np.nan
    return np.mean(np.abs((y_true[mask]-y_pred[mask])/y_true[mask]))*100

def smape(y_true, y_pred):
    return 100*np.mean(2*np.abs(y_pred-y_true)/(np.abs(y_true)+np.abs(y_pred)+1e-8))

def evaluate(y_true, y_pred, label=""):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    y_range = np.max(y_true)-np.min(y_true)
    nmae = mae/y_range
    nrmse = rmse/y_range
    acc = (1-nmae)*100
    mape = safe_mape(y_true,y_pred)
    smape_val = smape(y_true,y_pred)
    print(f"\n--- {label} ---")
    print(f"MAE={mae:.3f}, RMSE={rmse:.3f}, R²={r2:.4f}, NMAE={nmae:.4f}, NRMSE={nrmse:.4f}, Acc={acc:.2f}%")
    print(f"MAPE={mape:.2f}%, SMAPE={smape_val:.2f}%")
    return [mae,rmse,r2,nmae,nrmse,acc,mape,smape_val]

def build_lstm_feature_model(input_shape):
    inp = Input(shape=input_shape)
    x = LSTM(64, return_sequences=True)(inp)
    x = Dropout(0.2)(x)
    x = LSTM(64, return_sequences=False)(x)
    x = Dropout(0.2)(x)
    x = Dense(64, activation="relu")(x)
    feat = Dense(32, activation="relu", name="feature_vector")(x)
    out = Dense(1, activation="linear")(feat)
    return Model(inputs=inp, outputs=out)

# -------------------------
# Scaling & sequences
# -------------------------
scaler_X = MinMaxScaler()
scaler_pv, scaler_ld = MinMaxScaler(), MinMaxScaler()

X_all = scaler_X.fit_transform(df[FEATURES])
y_pv_all = scaler_pv.fit_transform(df[[TARGET_PV]])
y_ld_all = scaler_ld.fit_transform(df[[TARGET_LOAD]])

X_seq, y_pv_seq = create_sequences(X_all, y_pv_all, TIMESTEPS)
_, y_ld_seq     = create_sequences(X_all, y_ld_all, TIMESTEPS)

split_idx = int(0.8 * len(X_seq))
X_train, X_test = X_seq[:split_idx], X_seq[split_idx:]
y_pv_train, y_pv_test = y_pv_seq[:split_idx], y_pv_seq[split_idx:]
y_ld_train, y_ld_test = y_ld_seq[:split_idx], y_ld_seq[split_idx:]

# -------------------------
# Train LSTM feature models
# -------------------------
early = EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True, verbose=0)

# GHI feature model
model_pv = build_lstm_feature_model((TIMESTEPS, X_train.shape[2]))
model_pv.compile(optimizer=Adam(), loss="mse")
history_pv = model_pv.fit(X_train, y_pv_train, epochs=EPOCHS, batch_size=BATCH_SIZE,
             validation_split=0.1, verbose=2, callbacks=[early])

# Load feature model
model_ld = build_lstm_feature_model((TIMESTEPS, X_train.shape[2]))
model_ld.compile(optimizer=Adam(), loss="mse")
history_ld = model_ld.fit(X_train, y_ld_train, epochs=EPOCHS, batch_size=BATCH_SIZE,
             validation_split=0.1, verbose=2, callbacks=[early])

feature_model_pv = Model(model_pv.input, model_pv.get_layer("feature_vector").output)
feature_model_ld = Model(model_ld.input, model_ld.get_layer("feature_vector").output)

train_feats_pv = feature_model_pv.predict(X_train)
test_feats_pv = feature_model_pv.predict(X_test)
train_feats_ld = feature_model_ld.predict(X_train)
test_feats_ld = feature_model_ld.predict(X_test)

# -------------------------
# Train XGBoost regressors
# -------------------------
xgb_pv = xgb.XGBRegressor(n_estimators=400, learning_rate=0.03, max_depth=8,
                          subsample=0.9, colsample_bytree=0.9, tree_method="hist")
xgb_ld = xgb.XGBRegressor(n_estimators=400, learning_rate=0.03, max_depth=8,
                          subsample=0.9, colsample_bytree=0.9, tree_method="hist")
xgb_pv.fit(train_feats_pv, y_pv_train.flatten(), verbose=False)
xgb_ld.fit(train_feats_ld, y_ld_train.flatten(), verbose=False)

# -------------------------
# Predict
# -------------------------
t0 = time.time()
y_pv_pred_scaled = xgb_pv.predict(test_feats_pv).reshape(-1, 1)
y_ld_pred_scaled = xgb_ld.predict(test_feats_ld).reshape(-1, 1)
latency = (time.time()-t0) / len(X_test)

y_pv_pred = scaler_pv.inverse_transform(y_pv_pred_scaled).flatten()
y_ld_pred = scaler_ld.inverse_transform(y_ld_pred_scaled).flatten()
y_pv_true = scaler_pv.inverse_transform(y_pv_test).flatten()
y_ld_true = scaler_ld.inverse_transform(y_ld_test).flatten()

# -------------------------
# PV output & Net load
# -------------------------
predicted_pv_output_kw = y_pv_pred * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000.0
actual_pv_output_kw    = y_pv_true * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000.0

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw

# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true, y_pv_pred, "GHI → PV (LSTM+XGBoost)")
m_ld = evaluate(y_ld_true, y_ld_pred, "Load B4 (LSTM+XGBoost)")
m_net= evaluate(net_load_actual, net_load_pred, "Net Load (LSTM+XGBoost)")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot], label="Actual GHI")
plt.plot(y_pv_pred[:n_plot], label="Predicted GHI")
plt.title("Actual vs Predicted GHI (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot], label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot], label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4, LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot], label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot], label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot], label="Actual Net Load")
plt.plot(net_load_pred[:n_plot], label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False, suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
    xgb_pv.save_model(tmp.name)
    size_xgb_pv = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
    xgb_ld.save_model(tmp.name)
    size_xgb_ld = os.path.getsize(tmp.name) / 1e6
model_size = size_pv + size_ld + size_xgb_pv + size_xgb_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")

# ======================================
# 95% Confidence Interval for Net Load Forecasting
# ======================================

# Calculate absolute prediction errors
net_errors = np.abs(net_load_actual - net_load_pred)

# Mean Absolute Error
net_mae = np.mean(net_errors)

# Standard deviation of errors
net_std = np.std(net_errors, ddof=1)

# Number of test samples
n = len(net_errors)

# 95% confidence interval
margin_error = 1.96 * (net_std / np.sqrt(n))

ci_lower = net_mae - margin_error
ci_upper = net_mae + margin_error


print("\n========== Net Load Forecasting Confidence Interval ==========")
print(f"MAE: {net_mae:.4f}")
print(f"95% Confidence Interval: [{ci_lower:.4f}, {ci_upper:.4f}]")

early = EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True, verbose=0)
model_pv.fit(X_train, y_pv_train, epochs=EPOCHS, batch_size=BATCH_SIZE,
             validation_split=0.1, verbose=2, callbacks=[early])

plt.figure(figsize=(10, 6))
plt.plot(history_pv.history['loss'], label='GHI Training Loss')
plt.plot(history_pv.history['val_loss'], label='GHI Validation Loss')
plt.title('GHI Model Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(history_ld.history['loss'], label='Load B4 Training Loss')
plt.plot(history_ld.history['val_loss'], label='Load B4 Validation Loss')
plt.title('Load B4 Model Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(history_pv.history['loss'], label='GHI Training Loss')
plt.plot(history_pv.history['val_loss'], label='GHI Validation Loss')
plt.title('GHI Model Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(history_ld.history['loss'], label='Load B4 Training Loss')
plt.plot(history_ld.history['val_loss'], label='Load B4 Validation Loss')
plt.title('Load B4 Model Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

print("hello")

PANEL_AREA_M2    = 0.1
PANEL_EFFICIENCY = 0.20
# -------------------------
# Predict
# -------------------------
t0 = time.time()
y_pv_pred_scaled = xgb_pv.predict(test_feats_pv).reshape(-1, 1)
y_ld_pred_scaled = xgb_ld.predict(test_feats_ld).reshape(-1, 1)
latency = (time.time()-t0) / len(X_test)

y_pv_pred = scaler_pv.inverse_transform(y_pv_pred_scaled).flatten()
y_ld_pred = scaler_ld.inverse_transform(y_ld_pred_scaled).flatten()
y_pv_true = scaler_pv.inverse_transform(y_pv_test).flatten()
y_ld_true = scaler_ld.inverse_transform(y_ld_test).flatten()

# -------------------------
# PV output & Net load
# -------------------------
predicted_pv_output_kw = y_pv_pred * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000.0
actual_pv_output_kw    = y_pv_true * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000.0

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw

# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true, y_pv_pred, "GHI → PV (LSTM+XGBoost)")
m_ld = evaluate(y_ld_true, y_ld_pred, "Load B4 (LSTM+XGBoost)")
m_net= evaluate(net_load_actual, net_load_pred, "Net Load (LSTM+XGBoost)")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot], label="Actual GHI")
plt.plot(y_pv_pred[:n_plot], label="Predicted GHI")
plt.title("Actual vs Predicted GHI (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot], label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot], label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4, LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot], label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot], label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot], label="Actual Net Load")
plt.plot(net_load_pred[:n_plot], label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False, suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
    xgb_pv.save_model(tmp.name)
    size_xgb_pv = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
    xgb_ld.save_model(tmp.name)
    size_xgb_ld = os.path.getsize(tmp.name) / 1e6
model_size = size_pv + size_ld + size_xgb_pv + size_xgb_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")

# -------------------------
# Scatter Plots with Regression Line
# -------------------------
plt.figure(figsize=(6, 6))
plt.scatter(y_pv_true[:n_plot], y_pv_pred[:n_plot], alpha=0.6)
plt.plot([min(y_pv_true[:n_plot]), max(y_pv_true[:n_plot])], [min(y_pv_true[:n_plot]), max(y_pv_true[:n_plot])], color='red', linestyle='--')
plt.title("Actual vs Predicted GHI (LSTM+XGBoost)");
plt.xlabel("Actual GHI"); plt.ylabel("Predicted GHI");
plt.grid(True); plt.show()

plt.figure(figsize=(6, 6))
plt.scatter(y_ld_true[:n_plot], y_ld_pred[:n_plot], alpha=0.6)
plt.plot([min(y_ld_true[:n_plot]), max(y_ld_true[:n_plot])], [min(y_ld_true[:n_plot]), max(y_ld_true[:n_plot])], color='red', linestyle='--')
plt.title("Actual vs Predicted Load (B4, LSTM+XGBoost)");
plt.xlabel("Actual Load B4"); plt.ylabel("Predicted Load B4");
plt.grid(True); plt.show()

plt.figure(figsize=(10, 10))
plt.scatter(net_load_actual[:n_plot], net_load_pred[:n_plot], alpha=0.5)
plt.plot([min(net_load_actual[:n_plot]), max(net_load_actual[:n_plot])], [min(net_load_actual[:n_plot]), max(net_load_actual[:n_plot])], color='red', linestyle='--')
plt.title("Actual vs Predicted Net Load (LSTM+XGBoost)");
plt.xlabel("Actual Net Load"); plt.ylabel("Predicted Net Load");
plt.grid(True); plt.show()

from google.colab import drive
drive.mount('/content/drive')

import os, time, tempfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

import xgboost as xgb

# -------------------------
# Config
# -------------------------
FILE_WEATHER = "/content/drive/MyDrive/data/UTD_Weather.csv"
FILE_PV      = "/content/drive/MyDrive/data/UTD_Load.csv"

TIMESTEPS   = 48
BATCH_SIZE  = 32
EPOCHS      = 100
PATIENCE    = 15
THRESHOLD_DAY = 0.1
TARGET_PV   = "GHI"
TARGET_LOAD = "B4"

PANEL_AREA_M2    = 1.0
PANEL_EFFICIENCY = 0.20

# -------------------------
# Load & preprocess
# -------------------------
weather_df = pd.read_csv(FILE_WEATHER)
load_df    = pd.read_csv(FILE_PV)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp']    = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on="Timestamp", how="inner").sort_values("Timestamp").reset_index(drop=True)
df = df.dropna(subset=[TARGET_PV, TARGET_LOAD])

FEATURES = [c for c in df.columns if c not in ["Timestamp", TARGET_PV, TARGET_LOAD]]


# -------------------------
# Helpers
# -------------------------
def create_sequences(X, y, timesteps):
    Xs, ys = [], []
    for i in range(len(X) - timesteps):
        Xs.append(X[i:i+timesteps])
        ys.append(y[i+timesteps])
    return np.array(Xs), np.array(ys)

def safe_mape(y_true, y_pred):
    mask = y_true > THRESHOLD_DAY
    if mask.sum() == 0: return np.nan
    return np.mean(np.abs((y_true[mask]-y_pred[mask])/y_true[mask]))*100

def smape(y_true, y_pred):
    return 100*np.mean(2*np.abs(y_pred-y_true)/(np.abs(y_true)+np.abs(y_pred)+1e-8))

def evaluate(y_true, y_pred, label=""):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    y_range = np.max(y_true)-np.min(y_true)
    nmae = mae/y_range
    nrmse = rmse/y_range
    acc = (1-nmae)*100
    mape = safe_mape(y_true,y_pred)
    smape_val = smape(y_true,y_pred)
    print(f"\n--- {label} ---")
    print(f"MAE={mae:.3f}, RMSE={rmse:.3f}, R²={r2:.4f}, NMAE={nmae:.4f}, NRMSE={nrmse:.4f}, Acc={acc:.2f}%")
    print(f"MAPE={mape:.2f}%, SMAPE={smape_val:.2f}%")
    return [mae,rmse,r2,nmae,nrmse,acc,mape,smape_val]

def build_lstm_feature_model(input_shape):
    inp = Input(shape=input_shape)
    x = LSTM(64, return_sequences=True)(inp)
    x = Dropout(0.2)(x)
    x = LSTM(64, return_sequences=False)(x)
    x = Dropout(0.2)(x)
    x = Dense(64, activation="relu")(x)
    feat = Dense(32, activation="relu", name="feature_vector")(x)
    out = Dense(1, activation="linear")(feat)
    return Model(inputs=inp, outputs=out)

# -------------------------
# Scaling & sequences
# -------------------------
# ======================================
# Ablation Study:
# Without Feature Normalization
# ======================================

X_all = df[FEATURES].values

y_pv_all = df[[TARGET_PV]].values
y_ld_all = df[[TARGET_LOAD]].values

X_seq, y_pv_seq = create_sequences(X_all, y_pv_all, TIMESTEPS)
_, y_ld_seq     = create_sequences(X_all, y_ld_all, TIMESTEPS)

split_idx = int(0.8 * len(X_seq))
X_train, X_test = X_seq[:split_idx], X_seq[split_idx:]
y_pv_train, y_pv_test = y_pv_seq[:split_idx], y_pv_seq[split_idx:]
y_ld_train, y_ld_test = y_ld_seq[:split_idx], y_ld_seq[split_idx:]

# -------------------------
# Train LSTM feature models
# -------------------------
early = EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True, verbose=0)

# GHI feature model
model_pv = build_lstm_feature_model((TIMESTEPS, X_train.shape[2]))
model_pv.compile(optimizer=Adam(0.0001), loss="mse")
history_pv = model_pv.fit(X_train, y_pv_train, epochs=EPOCHS, batch_size=BATCH_SIZE,
             validation_split=0.1, verbose=2, callbacks=[early])

# Load feature model
model_ld = build_lstm_feature_model((TIMESTEPS, X_train.shape[2]))
model_ld.compile(optimizer=Adam(0.0001), loss="mse")
history_ld = model_ld.fit(X_train, y_ld_train, epochs=EPOCHS, batch_size=BATCH_SIZE,
             validation_split=0.1, verbose=2, callbacks=[early])

feature_model_pv = Model(model_pv.input, model_pv.get_layer("feature_vector").output)
feature_model_ld = Model(model_ld.input, model_ld.get_layer("feature_vector").output)

train_feats_pv = feature_model_pv.predict(X_train)
test_feats_pv = feature_model_pv.predict(X_test)
train_feats_ld = feature_model_ld.predict(X_train)
test_feats_ld = feature_model_ld.predict(X_test)

# -------------------------
# Train XGBoost regressors
# -------------------------
xgb_pv = xgb.XGBRegressor(n_estimators=400, learning_rate=0.03, max_depth=8,
                          subsample=0.9, colsample_bytree=0.9, tree_method="hist")
xgb_ld = xgb.XGBRegressor(n_estimators=400, learning_rate=0.03, max_depth=8,
                          subsample=0.9, colsample_bytree=0.9, tree_method="hist")
xgb_pv.fit(train_feats_pv, y_pv_train.flatten(), verbose=False)
xgb_ld.fit(train_feats_ld, y_ld_train.flatten(), verbose=False)

# -------------------------
# Predict
# -------------------------
t0 = time.time()
y_pv_pred_scaled = xgb_pv.predict(test_feats_pv).reshape(-1, 1)
y_ld_pred_scaled = xgb_ld.predict(test_feats_ld).reshape(-1, 1)
latency = (time.time()-t0) / len(X_test)

# Predictions already in original scale
y_pv_pred = y_pv_pred_scaled.flatten()
y_ld_pred = y_ld_pred_scaled.flatten()

y_pv_true = y_pv_test.flatten()
y_ld_true = y_ld_test.flatten()

# -------------------------
# PV output & Net load
# -------------------------
predicted_pv_output_kw = y_pv_pred * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000.0
actual_pv_output_kw    = y_pv_true * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000.0

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw

# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true, y_pv_pred, "GHI → PV (LSTM+XGBoost)")
m_ld = evaluate(y_ld_true, y_ld_pred, "Load B4 (LSTM+XGBoost)")
m_net= evaluate(net_load_actual, net_load_pred, "Net Load (LSTM+XGBoost)")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot], label="Actual GHI")
plt.plot(y_pv_pred[:n_plot], label="Predicted GHI")
plt.title("Actual vs Predicted GHI (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot], label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot], label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4, LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot], label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot], label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot], label="Actual Net Load")
plt.plot(net_load_pred[:n_plot], label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load (LSTM+XGBoost)"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False, suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
    xgb_pv.save_model(tmp.name)
    size_xgb_pv = os.path.getsize(tmp.name) / 1e6
with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
    xgb_ld.save_model(tmp.name)
    size_xgb_ld = os.path.getsize(tmp.name) / 1e6
model_size = size_pv + size_ld + size_xgb_pv + size_xgb_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")