# -*- coding: utf-8 -*-
"""LSTM+GRU fr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlafQ1xoCwdYr5qVC8M0YLLCxxLvl-h4
"""

# ======================================
# LSTM+GRU Hybrid for GHI & Load (B4)
# ======================================

import os, time, tempfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, GRU
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import MeanSquaredError # Import MeanSquaredError for saving/loading

# -------------------------
# Config
# -------------------------
FILE_WEATHER = "/content/drive/MyDrive/data/UTD_Weather.csv"
FILE_PV      = "/content/drive/MyDrive/data/UTD_Load.csv"

TIMESTEPS   = 48
BATCH_SIZE  = 32
EPOCHS      = 100
PATIENCE    = 15
THRESHOLD_DAY = 0.1
TARGET_PV   = "GHI"
TARGET_LOAD = "B4"

PANEL_AREA_M2    = 1950.0
PANEL_EFFICIENCY = 0.20

# -------------------------
# Load & preprocess
# -------------------------
weather_df = pd.read_csv(FILE_WEATHER)
load_df    = pd.read_csv(FILE_PV)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp']    = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on="Timestamp", how="inner").sort_values("Timestamp").reset_index(drop=True)
df = df.dropna(subset=[TARGET_PV, TARGET_LOAD])

# Define features including time features
BASE_FEATURES = ['Temperature', 'Dew.Point', 'Relative.Humidity', 'Pressure', 'Wind.Speed',
                 'Wind.Direction', 'Cloud.Type', 'Solar.Zenith.Angle', 'Precipitable.Water',
                 'DNI', 'DHI']

# Add time features
df['hour'] = df['Timestamp'].dt.hour
df['dayofweek'] = df['Timestamp'].dt.dayofweek
df['month'] = df['Timestamp'].dt.month
df['hour_sin']  = np.sin(2*np.pi*df['hour']/24)
df['hour_cos']  = np.cos(2*np.pi*df['hour']/24)
df['dow_sin']   = np.sin(2*np.pi*df['dayofweek']/7)
df['dow_cos']   = np.cos(2*np.pi*df['dayofweek']/7)
df['mon_sin']   = np.sin(2*np.pi*df['month']/12)
df['mon_cos']   = np.cos(2*np.pi*df['month']/12)
TIME_FEATS = ['hour_sin','hour_cos','dow_sin','dow_cos','mon_sin','mon_cos']
FEATURES = BASE_FEATURES + TIME_FEATS


# -------------------------
# Helpers
# -------------------------
def create_sequences(X, y, timesteps):
    Xs, ys = [], []
    for i in range(len(X) - timesteps):
        Xs.append(X[i:i+timesteps])
        ys.append(y[i+timesteps])
    return np.array(Xs), np.array(ys)

def safe_mape(y_true, y_pred):
    mask = y_true > THRESHOLD_DAY
    if mask.sum() == 0: return np.nan
    return np.mean(np.abs((y_true[mask]-y_pred[mask])/y_true[mask]))*100

def smape(y_true, y_pred):
    return 100*np.mean(2*np.abs(y_pred-y_true)/(np.abs(y_true)+np.abs(y_pred)+1e-8))

def evaluate(y_true, y_pred, label=""):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    y_range = np.max(y_true)-np.min(y_true)
    nmae = mae/y_range
    nrmse = rmse/y_range
    acc = (1-nmae)*100
    mape = safe_mape(y_true,y_pred)
    smape_val = smape(y_true,y_pred)

    print(f"\n--- {label} ---")
    print(f"MAE={mae:.3f}, RMSE={rmse:.3f}, R²={r2:.4f}, NMAE={nmae:.4f}, NRMSE={nrmse:.4f}, Acc={acc:.2f}%")
    print(f"MAPE={mape:.2f}%, SMAPE={smape_val:.2f}%")
    return [mae,rmse,r2,nmae,nrmse,acc,mape,smape_val]

def build_lstm_gru(input_shape):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        GRU(64, return_sequences=False),
        Dropout(0.2),
        Dense(64, activation="relu"),
        Dense(1, activation="linear")
    ])
    model.compile(optimizer=Adam(0.001),loss="mse")
    return model

# -------------------------
# Scaling & sequences
# -------------------------
scaler_X = MinMaxScaler()
scaler_pv, scaler_ld = MinMaxScaler(), MinMaxScaler()

X_all = scaler_X.fit_transform(df[FEATURES])
y_pv_all = scaler_pv.fit_transform(df[[TARGET_PV]])
y_ld_all = scaler_ld.fit_transform(df[[TARGET_LOAD]])

X_seq,y_pv_seq = create_sequences(X_all,y_pv_all,TIMESTEPS)
_,y_ld_seq     = create_sequences(X_all,y_ld_all,TIMESTEPS)

split_idx = int(0.8*len(X_seq))
X_train,X_test = X_seq[:split_idx],X_seq[split_idx:]
y_pv_train,y_pv_test = y_pv_seq[:split_idx],y_pv_seq[split_idx:]
y_ld_train,y_ld_test = y_ld_seq[:split_idx],y_ld_seq[split_idx:]

# -------------------------
# Train models
# -------------------------
early = EarlyStopping(monitor="val_loss",patience=PATIENCE,restore_best_weights=True)

model_pv = build_lstm_gru((TIMESTEPS,X_train.shape[2]))
model_pv.fit(X_train,y_pv_train,epochs=EPOCHS,batch_size=BATCH_SIZE,
             validation_split=0.1,verbose=2,callbacks=[early])

model_ld = build_lstm_gru((TIMESTEPS,X_train.shape[2]))
model_ld.fit(X_train,y_ld_train,epochs=EPOCHS,batch_size=BATCH_SIZE,
             validation_split=0.1,verbose=2,callbacks=[early])

# -------------------------
# Predict
# -------------------------
t0 = time.time()
y_pv_pred_scaled = model_pv.predict(X_test)
y_ld_pred_scaled = model_ld.predict(X_test)
latency = (time.time()-t0)/len(X_test)

y_pv_pred = scaler_pv.inverse_transform(y_pv_pred_scaled).flatten()
y_ld_pred = scaler_ld.inverse_transform(y_ld_pred_scaled).flatten()
y_pv_true = scaler_pv.inverse_transform(y_pv_test).flatten()
y_ld_true = scaler_ld.inverse_transform(y_ld_test).flatten()

# -------------------------
# PV output & Net load
# -------------------------
predicted_pv_output_kw = y_pv_pred*PANEL_AREA_M2*PANEL_EFFICIENCY*0.95/1000.0
actual_pv_output_kw    = y_pv_true*PANEL_AREA_M2*PANEL_EFFICIENCY/1000.0

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw

# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true,y_pv_pred,"GHI → PV")
m_ld = evaluate(y_ld_true,y_ld_pred,"Load B4")
m_net= evaluate(net_load_actual,net_load_pred,"Net Load")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot],label="Actual GHI")
plt.plot(y_pv_pred[:n_plot],label="Predicted GHI")
plt.title("Actual vs Predicted GHI"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot],label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot],label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot],label="Actual Net Load")
plt.plot(net_load_pred[:n_plot],label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name)/1e6
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name)/1e6
model_size = size_pv+size_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")

PANEL_AREA_M2    = 1950
PANEL_EFFICIENCY = 0.2
pr=0.9
predicted_pv_output_kw = y_pv_pred*PANEL_AREA_M2*PANEL_EFFICIENCY*0.9/1000
actual_pv_output_kw    = y_pv_true*PANEL_AREA_M2*PANEL_EFFICIENCY/1000

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw
# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true,y_pv_pred,"GHI → PV")
m_ld = evaluate(y_ld_true,y_ld_pred,"Load B4")
m_net= evaluate(net_load_actual,net_load_pred,"Net Load")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot],label="Actual GHI")
plt.plot(y_pv_pred[:n_plot],label="Predicted GHI")
plt.title("Actual vs Predicted GHI"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot],label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot],label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot],label="Actual Net Load")
plt.plot(net_load_pred[:n_plot],label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name)/1e6
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name)/1e6
model_size = size_pv+size_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")

# -------------------------
# Scatter Plots with Regression Line
# -------------------------
plt.figure(figsize=(6, 6))
plt.scatter(y_pv_true[:n_plot], y_pv_pred[:n_plot], alpha=0.6)
plt.plot([min(y_pv_true[:n_plot]), max(y_pv_true[:n_plot])], [min(y_pv_true[:n_plot]), max(y_pv_true[:n_plot])], color='red', linestyle='--')
plt.title("Actual vs Predicted GHI (LSTM+GRU)");
plt.xlabel("Actual GHI"); plt.ylabel("Predicted GHI");
plt.grid(True); plt.show()

plt.figure(figsize=(6, 6))
plt.scatter(y_ld_true[:n_plot], y_ld_pred[:n_plot], alpha=0.6)
plt.plot([min(y_ld_true[:n_plot]), max(y_ld_true[:n_plot])], [min(y_ld_true[:n_plot]), max(y_ld_true[:n_plot])], color='red', linestyle='--')
plt.title("Actual vs Predicted Load (B4, LSTM+GRU)");
plt.xlabel("Actual Load B4"); plt.ylabel("Predicted Load B4");
plt.grid(True); plt.show()

# =========================================
# Real-Time Simulation for LSTM+GRU Forecasting
# =========================================
import numpy as np
import pandas as pd
import time
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from IPython.display import clear_output
from tensorflow.keras.metrics import MeanSquaredError # Import MeanSquaredError

# -------------------------
# 1. Load Models
# -------------------------
# Provide the custom object 'mse' when loading the models
ghi_model = load_model('/content/drive/MyDrive/models/lstm_gru_ghi_model.h5', custom_objects={'mse': MeanSquaredError()})
load_model_b4 = load_model('/content/drive/MyDrive/models/lstm_gru_load_model.h5', custom_objects={'mse': MeanSquaredError()})

# -------------------------
# 2. Load Dataset
# -------------------------
weather_path = '/content/drive/MyDrive/data/UTD_Weather.csv'
load_path = '/content/drive/MyDrive/data/UTD_Load.csv'

weather_df = pd.read_csv(weather_path)
load_df = pd.read_csv(load_path)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp'] = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on='Timestamp', how='inner').sort_values('Timestamp').reset_index(drop=True)

!pip install streamlit tensorflow xgboost matplotlib scikit-learn pandas numpy

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import time
from tensorflow.keras.metrics import MeanSquaredError # Import MeanSquaredError

# -----------------------
# CONFIGURATION
# -----------------------
PANEL_AREA_M2 = 1950.0
PANEL_EFFICIENCY = 0.20
TIMESTEPS = 48
THRESHOLD_DAY = 0.1

st.set_page_config(page_title="Solar PV Forecasting Simulation", layout="wide")
st.title("🌞 Real-Time Simulation of Solar PV & Load Forecasting (LSTM+GRU)")

# -----------------------
# LOAD DATA
# -----------------------
weather_file = "/content/drive/MyDrive/data/UTD_Weather.csv"
load_file = "/content/drive/MyDrive/data/UTD_Load.csv"

weather_df = pd.read_csv(weather_file)
load_df = pd.read_csv(load_file)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp'] = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on='Timestamp', how='inner').sort_values('Timestamp').reset_index(drop=True)

target_building = "B4"
st.sidebar.header("Simulation Controls")
num_samples = st.sidebar.slider("Number of time steps to simulate:", 100, 2000, 500, step=100)

# -----------------------
# TIME FEATURES
# -----------------------
df['hour'] = df['Timestamp'].dt.hour
df['dayofweek'] = df['Timestamp'].dt.dayofweek
df['month'] = df['Timestamp'].dt.month
df['hour_sin'] = np.sin(2*np.pi*df['hour']/24)
df['hour_cos'] = np.cos(2*np.pi*df['hour']/24)
df['dow_sin'] = np.sin(2*np.pi*df['dayofweek']/7)
df['dow_cos'] = np.cos(2*np.pi*df['dayofweek']/7)
df['mon_sin'] = np.sin(2*np.pi*df['month']/12)
df['mon_cos'] = np.cos(2*np.pi*df['month']/12)

FEATURES = ['Temperature', 'Dew.Point', 'Relative.Humidity', 'Pressure', 'Wind.Speed',
            'Wind.Direction', 'Cloud.Type', 'Solar.Zenith.Angle', 'Precipitable.Water',
            'DNI', 'DHI', 'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos', 'mon_sin', 'mon_cos']

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()
X_all = scaler_X.fit_transform(df[FEATURES])
y_ghi = scaler_y.fit_transform(df[['GHI']])
y_load = scaler_y.fit_transform(df[[target_building]])

# -----------------------
# LOAD MODELS
# -----------------------
@st.cache_resource
def load_models():
    ghi_model = load_model("/content/drive/MyDrive/models/lstm_gru_ghi_model.h5",custom_objects={'mse': MeanSquaredError()})
    load_model_b4 = load_model("/content/drive/MyDrive/models/lstm_gru_load_model.h5",custom_objects={'mse': MeanSquaredError()})
    return ghi_model, load_model_b4

ghi_model, load_model_b4 = load_models()
st.success("✅ Models Loaded Successfully!")

# -----------------------
# SEQUENCE CREATION
# -----------------------
def create_sequences(X, y, timesteps):
    Xs, ys = [], []
    for i in range(len(X) - timesteps):
        Xs.append(X[i:i+timesteps])
        ys.append(y[i+timesteps])
    return np.array(Xs), np.array(ys)

X_seq_ghi, y_seq_ghi = create_sequences(X_all, y_ghi, TIMESTEPS)
X_seq_ld, y_seq_ld = create_sequences(X_all, y_load, TIMESTEPS)

split_idx = int(0.8 * len(X_seq_ghi))
X_test_ghi, y_test_ghi = X_seq_ghi[split_idx:], y_seq_ghi[split_idx:]
X_test_ld, y_test_ld = X_seq_ld[split_idx:], y_seq_ld[split_idx:]

# -----------------------
# SIMULATION LOOP
# -----------------------
placeholder1 = st.empty()
placeholder2 = st.empty()
placeholder3 = st.empty()

start_time = time.time()
preds_ghi = ghi_model.predict(X_test_ghi[:num_samples])
preds_load = load_model_b4.predict(X_test_ld[:num_samples])
latency = (time.time() - start_time) / num_samples

y_true_ghi = scaler_y.inverse_transform(y_test_ghi[:num_samples])
y_pred_ghi = scaler_y.inverse_transform(preds_ghi)
y_true_load = scaler_y.inverse_transform(y_test_ld[:num_samples])
y_pred_load = scaler_y.inverse_transform(preds_load)

# PV estimation
pred_pv_kw = y_pred_ghi * PANEL_AREA_M2 * PANEL_EFFICIENCY *0.95/ 1000.0
true_pv_kw = y_true_ghi * PANEL_AREA_M2 * PANEL_EFFICIENCY *0.95/ 1000.0

# Net load
pred_net = y_pred_load - pred_pv_kw
true_net = y_true_load - true_pv_kw

# -----------------------
# VISUALIZATION
# -----------------------
st.subheader("📊 Forecast Results Visualization")

fig1, ax1 = plt.subplots(figsize=(10,4))
ax1.plot(y_true_ghi[:num_samples], label="Actual GHI", linewidth=1)
ax1.plot(y_pred_ghi[:num_samples], label="Predicted GHI", linewidth=1)
ax1.set_title("Actual vs Predicted GHI")
ax1.legend(); ax1.grid(True)

fig2, ax2 = plt.subplots(figsize=(10,4))
ax2.plot(y_true_load[:num_samples], label="Actual Load (B4)", linewidth=1)
ax2.plot(y_pred_load[:num_samples], label="Predicted Load (B4)", linewidth=1)
ax2.set_title("Actual vs Predicted Load (B4)")
ax2.legend(); ax2.grid(True)

fig3, ax3 = plt.subplots(figsize=(10,4))
ax3.plot(true_net[:num_samples], label="Actual Net Load", linewidth=1)
ax3.plot(pred_net[:num_samples], label="Predicted Net Load", linewidth=1)
ax3.set_title("Predicted vs Actual Net Load")
ax3.legend(); ax3.grid(True)

placeholder1.pyplot(fig1)
placeholder2.pyplot(fig2)
placeholder3.pyplot(fig3)

# -----------------------
# PERFORMANCE SUMMARY
# -----------------------
st.subheader("📈 Model Performance Summary")
st.metric("Latency per Prediction", f"{latency:.4f} s")
st.metric("Model Size", "~1.38 MB (per model)")
st.success("Simulation complete. Forecasts generated successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import time
# from tensorflow.keras.models import load_model
# from tensorflow.keras.losses import MeanSquaredError
# 
# # Load trained models with custom loss handling
# mse = MeanSquaredError()
# 
# ghi_model = load_model('/content/drive/MyDrive/models/lstm_gru_ghi_model.h5', custom_objects={'mse': mse})
# load_model_b4 = load_model('/content/drive/MyDrive/models/lstm_gru_load_model.h5', custom_objects={'mse': mse})
# 
# # ----------------------------
# # Streamlit UI
# # ----------------------------
# st.title("🌤️ Real-Time Solar PV & Load Prediction Dashboard")
# 
# st.markdown("""
# This dashboard simulates real-time prediction of **Global Horizontal Irradiance (GHI)**,
# **Building Load (B4)**, and calculates the **Predicted PV Output** and **Net Load**
# using pre-trained LSTM + GRU hybrid models.
# """)
# 
# # Input sliders for simulation
# temp = st.slider("Temperature (°C)", 0, 45, 30)
# humidity = st.slider("Relative Humidity (%)", 0, 100, 60)
# wind = st.slider("Wind Speed (m/s)", 0, 15, 5)
# dni = st.slider("DNI (W/m²)", 0, 1000, 500)
# dhi = st.slider("DHI (W/m²)", 0, 500, 100)
# 
# if st.button("🔮 Predict Now"):
#     # Replace with real feature scaling if available
#     X_sample = np.random.rand(1, 48, 17)
# 
#     start_time = time.time()
#     ghi_pred = ghi_model.predict(X_sample)
#     load_pred = load_model_b4.predict(X_sample)
#     latency = time.time() - start_time
# 
#     # Convert GHI to PV Output
#     PANEL_AREA_M2 = 1.0
#     PANEL_EFFICIENCY = 0.20
#     pv_output = ghi_pred.mean() * PANEL_AREA_M2 * PANEL_EFFICIENCY / 1000
#     net_load = load_pred.mean() - pv_output
# 
#     # Display results
#     st.subheader("📊 Prediction Results")
#     st.metric("Predicted GHI", f"{ghi_pred.mean():.2f} W/m²")
#     st.metric("Predicted Load", f"{load_pred.mean():.2f} kW")
#     st.metric("Predicted PV Output", f"{pv_output:.4f} kW")
#     st.metric("Predicted Net Load", f"{net_load:.4f} kW")
#     st.info(f"⏱️ Inference Latency: {latency:.4f} seconds")
# 
#

# kill previous processes (ignore errors)
!pkill -f streamlit || true
!pkill -f localtunnel || true

# run streamlit in background
!nohup streamlit run app.py --server.port 8501 &> /content/streamlit.log &

!tail -n 50 /content/streamlit.log

!streamlit run app.py & npx localtunnel --port 8501

!curl -s ifconfig.me

!pip install streamlit pyngrok
!ngrok authtoken "2pBxHEBvZ3AYuQATnFFwyQ9F35f_4HRxcu25CLrkGBYh32TMa"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import tensorflow as tf
# import time
# from tensorflow.keras.models import load_model
# from tensorflow.keras.losses import MeanSquaredError
# 
# # Load trained models (from your Drive)
# ghi_model = load_model('/content/drive/MyDrive/models/lstm_gru_ghi_model.h5', custom_objects={'mse': MeanSquaredError()})
# load_model_b4 = load_model('/content/drive/MyDrive/models/lstm_gru_load_model.h5', custom_objects={'mse': MeanSquaredError()})
# 
# st.title("🌤️ Real-Time Solar PV & Load Prediction Dashboard")
# 
# # Input sliders
# temp = st.slider("Temperature (°C)", 0, 45, 30)
# humidity = st.slider("Relative Humidity (%)", 0, 100, 60)
# wind = st.slider("Wind Speed (m/s)", 0, 15, 5)
# dni = st.slider("DNI (W/m²)", 0, 1000, 500)
# dhi = st.slider("DHI (W/m²)", 0, 500, 100)
# 
# # Predict button
# if st.button("Predict"):
#     X_sample = np.random.rand(1, 48, 17)
#     start = time.time()
#     ghi_pred = ghi_model.predict(X_sample)
#     load_pred = load_model_b4.predict(X_sample)
#     latency = time.time() - start
# 
#     pv_output = ghi_pred.mean() * 0.2 / 1000
#     net_load = load_pred.mean() - pv_output
# 
#     st.metric("Predicted GHI", f"{ghi_pred.mean():.2f} W/m²")
#     st.metric("Predicted Load", f"{load_pred.mean():.2f} kW")
#     st.metric("Predicted PV Output", f"{pv_output:.2f} kW")
#     st.metric("Predicted Net Load", f"{net_load:.2f} kW")
#     st.write(f"⏱️ Inference Latency: {latency:.4f} seconds")
#

!streamlit run app.py & npx localtunnel --port 8501

!pip install ipywidgets tensorflow numpy matplotlib
from ipywidgets import interact, FloatSlider
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.losses import MeanSquaredError
import math
from IPython.display import clear_output

# Load models
ghi_model = load_model('/content/drive/MyDrive/models/lstm_gru_ghi_model.h5',
                       custom_objects={'mse': MeanSquaredError()})
load_model_b4 = load_model('/content/drive/MyDrive/models/lstm_gru_load_model.h5',
                           custom_objects={'mse': MeanSquaredError()})

# Panel & efficiency parameters (adjust as per your paper)
PANEL_AREA_M2 = 1950  # total rooftop area
PANEL_EFFICIENCY = 0.2  # 95%

def simulate_prediction(temp, humidity, wind, dni, dhi, zenith_angle):
    """
    Simulates model predictions with physical GHI computation.
    """
    # --- Compute actual GHI based on formula ---
    ghi_actual = dhi + dni * math.cos(math.radians(zenith_angle))

    # --- Prepare model input (scaled random for simulation) ---
    X_sample = np.random.rand(1, 48, 17)

    # --- Model predictions ---
    ghi_pred = ghi_model.predict(X_sample, verbose=0).mean() * 1000  # scale up
    load_pred = load_model_b4.predict(X_sample, verbose=0).mean() * 10  # scale up (typical kW range)

    # --- PV output based on predicted GHI ---
    pv_output = ghi_pred * PANEL_AREA_M2 * PANEL_EFFICIENCY *0.95/ 1000  # in kW
    net_load = load_pred - pv_output

    # --- Clear old plot ---
    clear_output(wait=True)

    # --- Display text output ---
    print(f"🌤️ Predicted GHI: {ghi_pred:.2f} W/m²")
    print(f"📈 Actual GHI (from formula): {ghi_actual:.2f} W/m²")
    print(f"⚡ Predicted Load (B4): {load_pred:.2f} kW")
    print(f"🔋 Predicted PV Output: {pv_output:.2f} kW")
    print(f"🔹 Predicted Net Load: {net_load:.2f} kW")

    # --- Plot Actual vs Predicted GHI ---
    fig, ax = plt.subplots(figsize=(6,4))
    ax.bar(['Actual GHI', 'Predicted GHI'], [ghi_actual, ghi_pred],
           color=['skyblue', 'orange'], alpha=0.8)
    ax.set_ylabel("GHI (W/m²)")
    ax.set_title("Actual vs Predicted GHI Comparison")
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()


# --- Interactive UI ---
interact(
    simulate_prediction,
    temp=FloatSlider(min=0, max=45, step=1, value=30, description='Temp (°C)'),
    humidity=FloatSlider(min=0, max=100, step=1, value=60, description='Humidity (%)'),
    wind=FloatSlider(min=0, max=15, step=0.5, value=5, description='Wind (m/s)'),
    dni=FloatSlider(min=0, max=1000, step=50, value=500, description='DNI (W/m²)'),
    dhi=FloatSlider(min=0, max=500, step=25, value=100, description='DHI (W/m²)'),
    zenith_angle=FloatSlider(min=0, max=90, step=1, value=30, description='Solar Zenith (°)')
)

# ======================================
# LSTM+GRU Hybrid for GHI & Load (B4)
# ======================================

import os, time, tempfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, GRU
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import MeanSquaredError # Import MeanSquaredError for saving/loading

# -------------------------
# Config
# -------------------------
FILE_WEATHER = "/content/drive/MyDrive/data/UTD_Weather.csv"
FILE_PV      = "/content/drive/MyDrive/data/UTD_Load.csv"

TIMESTEPS   = 48
BATCH_SIZE  = 32
EPOCHS      = 100
PATIENCE    = 15
THRESHOLD_DAY = 0.1
TARGET_PV   = "GHI"
TARGET_LOAD = "B4"

PANEL_AREA_M2    = 1950.0
PANEL_EFFICIENCY = 0.20

# -------------------------
# Load & preprocess
# -------------------------
weather_df = pd.read_csv(FILE_WEATHER)
load_df    = pd.read_csv(FILE_PV)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp']    = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on="Timestamp", how="inner").sort_values("Timestamp").reset_index(drop=True)
df = df.dropna(subset=[TARGET_PV, TARGET_LOAD])

# Define features including time features
BASE_FEATURES = ['Temperature', 'Dew.Point', 'Relative.Humidity', 'Pressure', 'Wind.Speed',
                 'Wind.Direction', 'Cloud.Type', 'Solar.Zenith.Angle', 'Precipitable.Water',
                 'DNI', 'DHI']

# Add time features
# ======================================
# Ablation Study:
# Without Cyclical Temporal Encoding
# ======================================

FEATURES = BASE_FEATURES


# -------------------------
# Helpers
# -------------------------
def create_sequences(X, y, timesteps):
    Xs, ys = [], []
    for i in range(len(X) - timesteps):
        Xs.append(X[i:i+timesteps])
        ys.append(y[i+timesteps])
    return np.array(Xs), np.array(ys)

def safe_mape(y_true, y_pred):
    mask = y_true > THRESHOLD_DAY
    if mask.sum() == 0: return np.nan
    return np.mean(np.abs((y_true[mask]-y_pred[mask])/y_true[mask]))*100

def smape(y_true, y_pred):
    return 100*np.mean(2*np.abs(y_pred-y_true)/(np.abs(y_true)+np.abs(y_pred)+1e-8))

def evaluate(y_true, y_pred, label=""):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    y_range = np.max(y_true)-np.min(y_true)
    nmae = mae/y_range
    nrmse = rmse/y_range
    acc = (1-nmae)*100
    mape = safe_mape(y_true,y_pred)
    smape_val = smape(y_true,y_pred)

    print(f"\n--- {label} ---")
    print(f"MAE={mae:.3f}, RMSE={rmse:.3f}, R²={r2:.4f}, NMAE={nmae:.4f}, NRMSE={nrmse:.4f}, Acc={acc:.2f}%")
    print(f"MAPE={mape:.2f}%, SMAPE={smape_val:.2f}%")
    return [mae,rmse,r2,nmae,nrmse,acc,mape,smape_val]

def build_lstm_gru(input_shape):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        GRU(64, return_sequences=False),
        Dropout(0.2),e
        Dense(64, activation="relu"),
        Dense(1, activation="linear")
    ])
    model.compile(optimizer=Adam(0.001),loss="mse")
    return model

# -------------------------
# Scaling & sequences
# -------------------------
scaler_X = MinMaxScaler()
scaler_pv, scaler_ld = MinMaxScaler(), MinMaxScaler()

X_all = scaler_X.fit_transform(df[FEATURES])
y_pv_all = scaler_pv.fit_transform(df[[TARGET_PV]])
y_ld_all = scaler_ld.fit_transform(df[[TARGET_LOAD]])

X_seq,y_pv_seq = create_sequences(X_all,y_pv_all,TIMESTEPS)
_,y_ld_seq     = create_sequences(X_all,y_ld_all,TIMESTEPS)

split_idx = int(0.8*len(X_seq))
X_train,X_test = X_seq[:split_idx],X_seq[split_idx:]
y_pv_train,y_pv_test = y_pv_seq[:split_idx],y_pv_seq[split_idx:]
y_ld_train,y_ld_test = y_ld_seq[:split_idx],y_ld_seq[split_idx:]

# -------------------------
# Train models
# -------------------------
early = EarlyStopping(monitor="val_loss",patience=PATIENCE,restore_best_weights=True)

model_pv = build_lstm_gru((TIMESTEPS,X_train.shape[2]))
model_pv.fit(X_train,y_pv_train,epochs=EPOCHS,batch_size=BATCH_SIZE,
             validation_split=0.1,verbose=2,callbacks=[early])

model_ld = build_lstm_gru((TIMESTEPS,X_train.shape[2]))
model_ld.fit(X_train,y_ld_train,epochs=EPOCHS,batch_size=BATCH_SIZE,
             validation_split=0.1,verbose=2,callbacks=[early])

# -------------------------
# Predict
# -------------------------
t0 = time.time()
y_pv_pred_scaled = model_pv.predict(X_test)
y_ld_pred_scaled = model_ld.predict(X_test)
latency = (time.time()-t0)/len(X_test)

y_pv_pred = scaler_pv.inverse_transform(y_pv_pred_scaled).flatten()
y_ld_pred = scaler_ld.inverse_transform(y_ld_pred_scaled).flatten()
y_pv_true = scaler_pv.inverse_transform(y_pv_test).flatten()
y_ld_true = scaler_ld.inverse_transform(y_ld_test).flatten()

# -------------------------
# PV output & Net load
# -------------------------
predicted_pv_output_kw = y_pv_pred*PANEL_AREA_M2*PANEL_EFFICIENCY*0.95/1000.0
actual_pv_output_kw    = y_pv_true*PANEL_AREA_M2*PANEL_EFFICIENCY/1000.0

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw

# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true,y_pv_pred,"GHI → PV")
m_ld = evaluate(y_ld_true,y_ld_pred,"Load B4")
m_net= evaluate(net_load_actual,net_load_pred,"Net Load")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot],label="Actual GHI")
plt.plot(y_pv_pred[:n_plot],label="Predicted GHI")
plt.title("Actual vs Predicted GHI"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot],label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot],label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot],label="Actual Net Load")
plt.plot(net_load_pred[:n_plot],label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name)/1e6
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name)/1e6
model_size = size_pv+size_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")



# ======================================
# LSTM+GRU Hybrid for GHI & Load (B4)
# ======================================

import os, time, tempfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, GRU
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import MeanSquaredError # Import MeanSquaredError for saving/loading

# -------------------------
# Config
# -------------------------
FILE_WEATHER = "/content/drive/MyDrive/data/UTD_Weather.csv"
FILE_PV      = "/content/drive/MyDrive/data/UTD_Load.csv"

TIMESTEPS   = 48
BATCH_SIZE  = 32
EPOCHS      = 100
PATIENCE    = 15
THRESHOLD_DAY = 0.1
TARGET_PV   = "GHI"
TARGET_LOAD = "B4"

PANEL_AREA_M2    = 1950.0
PANEL_EFFICIENCY = 0.20

# -------------------------
# Load & preprocess
# -------------------------
weather_df = pd.read_csv(FILE_WEATHER)
load_df    = pd.read_csv(FILE_PV)

weather_df['Timestamp'] = pd.to_datetime(weather_df['Timestamp'])
load_df['Timestamp']    = pd.to_datetime(load_df['Timestamp'])
df = pd.merge(weather_df, load_df, on="Timestamp", how="inner").sort_values("Timestamp").reset_index(drop=True)
df = df.dropna(subset=[TARGET_PV, TARGET_LOAD])

# Define features including time features
BASE_FEATURES = ['Temperature', 'Dew.Point', 'Relative.Humidity', 'Pressure', 'Wind.Speed',
                 'Wind.Direction', 'Cloud.Type', 'Solar.Zenith.Angle', 'Precipitable.Water',
                 'DNI', 'DHI']

# Add time features
df['hour'] = df['Timestamp'].dt.hour
df['dayofweek'] = df['Timestamp'].dt.dayofweek
df['month'] = df['Timestamp'].dt.month
df['hour_sin']  = np.sin(2*np.pi*df['hour']/24)
df['hour_cos']  = np.cos(2*np.pi*df['hour']/24)
df['dow_sin']   = np.sin(2*np.pi*df['dayofweek']/7)
df['dow_cos']   = np.cos(2*np.pi*df['dayofweek']/7)
df['mon_sin']   = np.sin(2*np.pi*df['month']/12)
df['mon_cos']   = np.cos(2*np.pi*df['month']/12)
TIME_FEATS = ['hour_sin','hour_cos','dow_sin','dow_cos','mon_sin','mon_cos']
FEATURES = BASE_FEATURES + TIME_FEATS


# -------------------------
# Helpers
# -------------------------
def create_sequences(X, y, timesteps):
    Xs, ys = [], []
    for i in range(len(X) - timesteps):
        Xs.append(X[i:i+timesteps])
        ys.append(y[i+timesteps])
    return np.array(Xs), np.array(ys)

def safe_mape(y_true, y_pred):
    mask = y_true > THRESHOLD_DAY
    if mask.sum() == 0: return np.nan
    return np.mean(np.abs((y_true[mask]-y_pred[mask])/y_true[mask]))*100

def smape(y_true, y_pred):
    return 100*np.mean(2*np.abs(y_pred-y_true)/(np.abs(y_true)+np.abs(y_pred)+1e-8))

def evaluate(y_true, y_pred, label=""):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    y_range = np.max(y_true)-np.min(y_true)
    nmae = mae/y_range
    nrmse = rmse/y_range
    acc = (1-nmae)*100
    mape = safe_mape(y_true,y_pred)
    smape_val = smape(y_true,y_pred)

    print(f"\n--- {label} ---")
    print(f"MAE={mae:.3f}, RMSE={rmse:.3f}, R²={r2:.4f}, NMAE={nmae:.4f}, NRMSE={nrmse:.4f}, Acc={acc:.2f}%")
    print(f"MAPE={mape:.2f}%, SMAPE={smape_val:.2f}%")
    return [mae,rmse,r2,nmae,nrmse,acc,mape,smape_val]

def build_lstm_gru(input_shape):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        GRU(64, return_sequences=False),
        Dropout(0.2),
        Dense(64, activation="relu"),
        Dense(1, activation="linear")
    ])
    model.compile(optimizer=Adam(0.0001),loss="mse")
    return model

# -------------------------
# Scaling & sequences
# -------------------------
# ======================================
# Ablation Study:
# Without Feature Normalization
# ======================================

X_all = df[FEATURES].values

y_pv_all = df[[TARGET_PV]].values
y_ld_all = df[[TARGET_LOAD]].values

X_seq,y_pv_seq = create_sequences(X_all,y_pv_all,TIMESTEPS)
_,y_ld_seq     = create_sequences(X_all,y_ld_all,TIMESTEPS)

split_idx = int(0.8*len(X_seq))
X_train,X_test = X_seq[:split_idx],X_seq[split_idx:]
y_pv_train,y_pv_test = y_pv_seq[:split_idx],y_pv_seq[split_idx:]
y_ld_train,y_ld_test = y_ld_seq[:split_idx],y_ld_seq[split_idx:]

# -------------------------
# Train models
# -------------------------
early = EarlyStopping(monitor="val_loss",patience=PATIENCE,restore_best_weights=True)

model_pv = build_lstm_gru((TIMESTEPS,X_train.shape[2]))
model_pv.fit(X_train,y_pv_train,epochs=EPOCHS,batch_size=BATCH_SIZE,
             validation_split=0.1,verbose=2,callbacks=[early])

model_ld = build_lstm_gru((TIMESTEPS,X_train.shape[2]))
model_ld.fit(X_train,y_ld_train,epochs=EPOCHS,batch_size=BATCH_SIZE,
             validation_split=0.1,verbose=2,callbacks=[early])

# -------------------------
# Predict
# -------------------------
t0 = time.time()
y_pv_pred_scaled = model_pv.predict(X_test)
y_ld_pred_scaled = model_ld.predict(X_test)
latency = (time.time()-t0)/len(X_test)

# Predictions already in original scale
y_pv_pred = y_pv_pred_scaled.flatten()
y_ld_pred = y_ld_pred_scaled.flatten()

y_pv_true = y_pv_test.flatten()
y_ld_true = y_ld_test.flatten()

# -------------------------
# PV output & Net load
# -------------------------
predicted_pv_output_kw = y_pv_pred*PANEL_AREA_M2*PANEL_EFFICIENCY*0.95/1000.0
actual_pv_output_kw    = y_pv_true*PANEL_AREA_M2*PANEL_EFFICIENCY/1000.0

net_load_pred   = y_ld_pred - predicted_pv_output_kw
net_load_actual = y_ld_true - actual_pv_output_kw

# -------------------------
# Metrics
# -------------------------
m_pv = evaluate(y_pv_true,y_pv_pred,"GHI → PV")
m_ld = evaluate(y_ld_true,y_ld_pred,"Load B4")
m_net= evaluate(net_load_actual,net_load_pred,"Net Load")

# -------------------------
# Plots
# -------------------------
n_plot = 500
plt.figure(figsize=(14,5))
plt.plot(y_pv_true[:n_plot],label="Actual GHI")
plt.plot(y_pv_pred[:n_plot],label="Predicted GHI")
plt.title("Actual vs Predicted GHI"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(y_ld_true[:n_plot],label="Actual Load B4")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Actual vs Predicted Load (B4)"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(predicted_pv_output_kw[:n_plot],label="Predicted PV Output (kW)")
plt.plot(y_ld_pred[:n_plot],label="Predicted Load B4")
plt.title("Predicted PV vs Predicted Load"); plt.legend(); plt.grid(True); plt.show()

plt.figure(figsize=(14,5))
plt.plot(net_load_actual[:n_plot],label="Actual Net Load")
plt.plot(net_load_pred[:n_plot],label="Predicted Net Load")
plt.title("Actual vs Predicted Net Load"); plt.legend(); plt.grid(True); plt.show()

# -------------------------
# Model size
# -------------------------
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_pv.save(tmp.name)
    size_pv = os.path.getsize(tmp.name)/1e6
with tempfile.NamedTemporaryFile(delete=False,suffix=".h5") as tmp:
    model_ld.save(tmp.name)
    size_ld = os.path.getsize(tmp.name)/1e6
model_size = size_pv+size_ld

print(f"\nLatency per sample: {latency*1000:.3f} ms")
print(f"Model size: {model_size:.2f} MB")